### ISSUE TITLE
请问，dpkg提示不是pcapng格式怎么解决

### ISSUE THREAD

**Issue by littleheary** [scu-igroup/ctf_ics_traffic#1]
现在脚本运行不了，报错如下：
it is not pcapng format...
Traceback (most recent call last):
  File "check_middler.py", line 48, in <module>
    pcap = dpkt.pcap.Reader(f)
  File "D:\work tools\python2\lib\site-packages\dpkt\pcap.py", line 245, in __init__
    self.__fh = FileHdr(buf)
  File "D:\work tools\python2\lib\site-packages\dpkt\dpkt.py", line 92, in __init__
    raise NeedData
dpkt.dpkt.NeedData

请问这个怎么解决？

**Comment by diablov** [comment]
同样问题，linux下也跑不了，这个dpkt的库是不是有局限？
